[package]
name = "device_video"
version = "0.1.0"
edition = "2021"

[dependencies]
peripheral_bus = { path = "../peripheral-bus" }
log = "0.4.21"
minifb = "0.28"
modular-bitfield = "0.13.0"

[dev-dependencies]
image = "0.25.6"
insta = { version = "1.43.1", features = ["yaml"] }
oxipng = "10.0.0"